In [7]:
# Tuto naive bayes

import numpy as np
import pandas as pd
import glob 
from sklearn.feature_extraction.text import CountVectorizer



In [3]:
# 1- load data
files=glob.glob('data\\*.csv')
files

['data\\Youtube01.csv',
 'data\\Youtube02.csv',
 'data\\Youtube03.csv',
 'data\\Youtube04.csv',
 'data\\Youtube05.csv']

In [4]:
all_df=[]
for i in files :
    all_df.append(pd.read_csv(i))

data = pd.concat(all_df, axis=0, ignore_index=True)

In [5]:
data.isnull().sum() #to check is there is null values in the data set, applying the sum gives us the number of null val

COMMENT_ID      0
AUTHOR          0
DATE          245
CONTENT         0
CLASS           0
dtype: int64

In [6]:
data['CLASS'].value_counts() # to see how much hums and spams we have

1    1004
0     951
Name: CLASS, dtype: int64

Naive Bayes is adapted to balanced datasets so for (1004,951) it is good 

In [9]:
msg=['Hello my darling good good morning']
countV= CountVectorizer() 
countV.fit(msg)
print(countV.transform(msg).toarray())   # tranform is for testing the model trained before
countV.get_feature_names_out()

[[1 2 1 1 1]]


array(['darling', 'good', 'hello', 'morning', 'my'], dtype=object)

Count Vectorizer is a class that creates a list that contains the words (strings) composed from 2 or more letters and give how much times does this word appear in the sentence

In [12]:
print(countV.transform(['Hello baby boy good evening']).toarray()) # doesnt take into consideration the capital letters

[[0 1 1 0 0]]


In [15]:
he=['Hihi huhu haha','haha hyhy hiiii']
print(countV.fit_transform(he).toarray())   # we can fit andtransform the model on 2 different strings and it treats em 
countV.get_feature_names_out()                                           # separaly

[[1 1 0 1 0]
 [1 0 1 0 1]]


array(['haha', 'hihi', 'hiiii', 'huhu', 'hyhy'], dtype=object)